export const COLOR = {
  BRAND: 'brand',
  BRAND_DARKER: 'brand-darker',
  BACKGROUND: 'background',
  SELECTED: 'selected',
  SELECTED_BACKGROUND: 'selected-background',
  GRAY_DARKER: 'gray-darker',
  GRAY_DARK: 'gray-dark',
  GRAY_LIGHT: 'gray-light',
  GRAY_LIGHTER: 'gray-lighter',
  TEXT: 'text',
  SUBTEXT: 'subtext',
  SUCCESS: 'success',
  ATTENTION: 'attention',
  WAIT: 'wait',
  ERROR: 'error',
  PRIMARY: 'primary',
  SECONDARY: 'secondary',
  FORM_BACKGROUND: 'form-background',
  CHECKED: 'checked',
} as const
