name: Firestore Security Rules Unit Tests

on:
  pull_request:
    branches:
      - develop
      - staging
      - main
    paths:
      - firebase/firestore.rules
      - firebase/firestore/**

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install firebase-tools
        run: npm install -g firebase-tools

      - name: Install packages
        run: yarn

      - name: Start Emulator
        run: firebase emulators:start --only firestore &
        working-directory: firebase

      - name: Wait for emulator to start
        run: sleep 10

      - name: Execute test codes
        run: yarn firestore test --silent --detectOpenHandles
